"use strict";

var jwt = require("jsonwebtoken");
const KEY = "F0od@ndDrugsAdm1n$tr@t!0n";

function validateSession(req, res, callback) {
  var token = "";

  if (req.headers && req.headers.authorization) {
    var header = req.headers.authorization.split(" ");
    token = header[1];
  }

  jwt.verify(token, KEY, (err, decoded) => {
    if (err) {
      res.status(401).send(err);
      callback(true, res);
    } else {
      res.status(200);
      callback(false, res);
    }
  });
}

/**
 * @description This is a test function, token should be generated by the auth micro service
 *
 */
function generateToken() {
  var token = jwt.sign({ test: "test" }, KEY, {
    expiresIn: "1m"
  });
  return token;
}

module.exports = {
  validateSession,
  generateToken
};
